Cppinecone: include/pinecone/domain/operation_type.hpp File Reference
operation_type.hpp File Reference
Operations made available by the Pinecone API.
#include "pinecone/domain/method.hpp"
Enumerations
enum class pinecone::domain::operation_type {
actions_whoami , index_create , index_configure , index_list ,
index_describe , index_delete , collection_create , collection_list ,
collection_describe , collection_delete , vector_upsert , vector_update ,
vector_query , vector_fetch , vector_describe_index_stats , vector_delete
}
All operation types exposed by the Pinecone REST API.
enum class pinecone::domain::api_type { controller , service }
The API types supported by the Pinecone REST API.
Functions
constexpr auto pinecone::domain::op_api_type (operation_type op) -> api_type
Returns the API type of an operation.
constexpr auto pinecone::domain::op_url_fragment (operation_type op) -> char const *
Returns the URL specialization for an operation.
constexpr auto pinecone::domain::op_method (operation_type op) -> method
Returns the HTTP method for an operation.
Detailed Description
Operations made available by the Pinecone API.
Definition in file operation_type.hpp.
Enumeration Type Documentation
api_type
enum pinecone::domain::api_type strong
The API types supported by the Pinecone REST API.
The Pinecone API is structured as two basic APIs:
The controller API, which allows users to create, configure, and delete indexes and collections
The vector API, which allows users to upsert, update, query, and delete vectors
Each operation_type is associated with one of these two APIs.
Definition at line 54 of file operation_type.hpp.
operation_type
enum pinecone::domain::operation_type strong
All operation types exposed by the Pinecone REST API.
Operation types can be understood within three general categories:
Index operations
Collection operations
Vector operations
Definition at line 21 of file operation_type.hpp.
Function Documentation
op_api_type()
constexpr auto pinecone::domain::op_api_type (operation_type op) -> api_type constexpr
Returns the API type of an operation.
Parameters
op the operation to query
Returns
the API type for the operation
Definition at line 65 of file operation_type.hpp.
Referenced by pinecone::domain::build_url(), and pinecone::domain::op_api_type().
op_method()
constexpr auto pinecone::domain::op_method (operation_type op) -> method constexpr
Returns the HTTP method for an operation.
Parameters
op the operation to query
Returns
the HTTP method for the operation
Definition at line 134 of file operation_type.hpp.
Referenced by pinecone::domain::op_method().
op_url_fragment()
constexpr auto pinecone::domain::op_url_fragment (operation_type op) -> char const* constexpr
Returns the URL specialization for an operation.
Parameters
op the operation to query
Returns
the URL suffix for the operation
Definition at line 95 of file operation_type.hpp.
Referenced by pinecone::domain::op_url_fragment().